### ISSUE TITLE
Engine mesh errors creating incompatibility with FAR in VSR 1.9.4

### ISSUE THREAD

**Issue by ferram4** [VenVen/Stock-Revamp#88]
Note: copy of text from thread post

It looks like your new models for the Mainsail, Skipper, Rhino, and I believe the Poodle and Terrier as well all cause voxelization errors with FAR.  All of the resulting behavior points to vertexes or triangles of either mesh or collider floating WAY out beyond the rest of the model, screwing up all attempts to figure out the bounds of the vehicle.  This will also cause issues with stock drag and heating as well, if that concerns you.

**Comment by VenVen** [comment]
Ah alright, that makes sense. I probably left some stray geometry after I finished UV unwrapping the models.  Nice to finally get a lead on how to fix the problem.

Thanks!

**Comment by NathanKell** [comment]
@VenVen sadly I'm having to hold RO at using only 1.9.2 until this gets fixed. Is there anything I can do to help?

**Comment by VenVen** [comment]
@ferram4 How can I tell if i've fixed the voxelization errors? Is the ingame FAR Analysis 'Desplay Debug Voxels' enough?

@NathanKell Unfortunately not, unless you say something that gets me back to modding KSP, Because for the last few months I've had no drive to continue working on it.

**Comment by ferram4** [comment]
@VenVen The display debug voxels should be good confirmation; the icons shouldn't be all that big and if they're at the density they should be at for one or two small parts you'll get significant lag because Unity rendering.  The other two tests are in the same exact editor GUI as the debug voxel display; the Mach 1 drag should be a finite number of some kind (not NaN) and the Max Cross-section Area should be approximately what you'd expect based on the max diameter of the part.

**Comment by NathanKell** [comment]
@VenVen Well, I can talk about how much 1.1.3 fixes, and the awesome plans we have for 1.2....? And how amazing your stuff is and how much we love it?

**Comment by ryanchristie** [comment]
@VenVen I can't play stock KSP anymore without your models and textures. I've wondered why Squad hasn't bought it and/or you by now. Your mod is to ships what EVE is to environments. I know squat about modding KSP or building 3D models - wish I could help.

**Comment by rsparkyc** [comment]
@VenVen 😢  Hopefully somewhere deep inside you'll find the desire to continue modding.

**Comment by NathanKell** [comment]
@VenVen should RO include the 1.9.2 engine files meanwhile? I rather hate to increase our download size, but I also hate to force a 1.9.2 dependency since it has other issues...

**Comment by NathanKell** [comment]
@VenVen due to the serious issues here, if you don't mind I'm going to release 1.9.5 with the problem-causing engine models reverted, and then when you have a chance you can re-add the fixed versions of the new models. That will also take care of updating the versioning so it's stated as KSP 1.1.3 compatible.

**Comment by NathanKell** [comment]
(Releasing will also fix an issue with CKAN: since no actual release zip was uploaded for 1.9.4, CKAN doesn't know it exists).

**Comment by VenVen** [comment]
I believe that I've fixed the engine voxel issues, as it turned out the position and scale of the rigged hose mesh I used does matter, and I had to zero out a bunch of values.

Other than that, I fixed the LV-900's animation.

**Comment by NathanKell** [comment]
@VenVen awesome! Thanks so much! We'll give it a test and if all's well push a release.

@ferram4 @Theysen

**Comment by Theysen** [comment]
After a quick look at all of the engines inside FAR analysis there are no issues remaining, except the Rhino. 
The static still gives NaN (if analysed alone) and the voxels are still bigger than normal but the geometry is absolutely fine and it didn't do crazy stuff during a testflight with other parts on top. So as far as I can see it it should all be good! Thanks so much @VenVen.

@NathanKell @ferram4

**Comment by thomas15v** [comment]
![image](https://cloud.githubusercontent.com/assets/2163941/21659635/fa76400e-d2cb-11e6-898a-5777ab8d3af2.png)
I wonder if this issue is related to this one. This is without FAR but it looks like the stock aerodynamics are also not being happy with this engine

**Comment by blowfishpro** [comment]
@thomas15v I don't think it's the same problem.  You're probably looking at the issue which is fixed here: https://github.com/VenVen/Stock-Revamp/pull/98 (note that the fix has not been released yet)
